//! Skill discovery on disk.
//!
//! A skill is a directory under `{app_data_dir}/skills/` holding a `SKILL.md`
//! with YAML frontmatter (`name`, `description`) plus optional bundled files.
//! The filesystem owns the content; the `skills` table only indexes it.
//!
//! Unlike project instructions this stays enabled on Android: the skills root
//! lives in app-private storage, which needs no SAF grant.

use std::path::{Path, PathBuf};

use diesel::sqlite::SqliteConnection;

use super::project_instructions::{MAX_FILE_SIZE, compute_mtime_hash, read_file_utf8};
use crate::db;
use crate::db::models::skill::{SkillInsert, SkillRow};
use crate::db::models::skill_binding::SkillLayer;
use crate::util::now_ms;

/// Cap on how much of SKILL.md is read while scanning. Frontmatter sits at the
/// top, so scanning never needs the body — this bounds a directory sweep to a
/// few KB per skill no matter how large the bodies are.
const FRONTMATTER_SCAN_BYTES: usize = 8 * 1024;

/// Descriptions are what sit in context on every single request, so they get a
/// hard character cap independent of the token budget.
pub(crate) const MAX_DESCRIPTION_LEN: usize = 200;

/// Upper bound on skills offered to a model at once. Beyond this the list stops
/// being a menu and starts being a tax.
pub(crate) const MAX_AVAILABLE_SKILLS: usize = 50;

pub const SKILL_FILE: &str = "SKILL.md";
pub const REFERENCES_DIR: &str = "references";

/// Marks a SKILL.md as one the app generates. Built-in skills are rewritten on
/// every launch, so this is how a launch tells its own file from one a user
/// happened to give the same directory name.
pub(crate) const GENERATED_MARKER: &str = "generated by Meridian";

/// Move a directory aside if it holds a skill the app did not write.
///
/// A user directory colliding with a built-in name would otherwise be
/// reclassified as official — uneditable, undeletable, and overwritten on the
/// next launch. Renaming turns silent data loss into something recoverable.
pub(crate) fn preserve_user_directory(dir: &Path) -> std::io::Result<()> {
    let skill_file = dir.join(SKILL_FILE);
    if !skill_file.exists() {
        return Ok(());
    }
    if std::fs::read_to_string(&skill_file)
        .unwrap_or_default()
        .contains(GENERATED_MARKER)
    {
        return Ok(());
    }

    let name = dir.file_name().and_then(|n| n.to_str()).unwrap_or("skill").to_string();
    let mut backup = dir.with_file_name(format!("{name}.user-backup"));
    // Never clobber an earlier backup either.
    let mut suffix = 2;
    while backup.exists() {
        backup = dir.with_file_name(format!("{name}.user-backup-{suffix}"));
        suffix += 1;
    }
    std::fs::rename(dir, &backup)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillMeta {
    pub dir_name: String,
    pub llm_name: String,
    pub llm_description: String,
    pub mtime_hash: String,
}

/// Directory and frontmatter `name` values must be slugs. This is both a
/// path-traversal guard and a provider constraint: tool/enum values containing
/// spaces or dots get rejected upstream.
pub fn is_valid_slug(s: &str) -> bool {
    !s.is_empty()
        && s.len() <= 64
        && s.chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
        && !s.starts_with('-')
        && !s.ends_with('-')
}

/// Pull `name` and `description` out of a leading `---` block. Deliberately not
/// a YAML parser: the two fields we need are plain `key: value` scalars, and a
/// real YAML dependency would let skill files express far more than we want to
/// honour.
pub fn parse_frontmatter(content: &str) -> Option<(String, String)> {
    let rest = content.strip_prefix("---")?;
    let rest = rest.strip_prefix("\r\n").or_else(|| rest.strip_prefix('\n'))?;
    let end = rest.find("\n---")?;

    let mut name = None;
    let mut description = None;
    for line in rest[..end].lines() {
        let line = line.trim_end_matches('\r');
        let Some((key, value)) = line.split_once(':') else {
            continue;
        };
        let value = value.trim().trim_matches('"').trim_matches('\'').trim();
        if value.is_empty() {
            continue;
        }
        match key.trim() {
            "name" => name = Some(value.to_string()),
            "description" => description = Some(value.to_string()),
            _ => {}
        }
    }
    Some((name?, description?))
}

/// Read only the head of a file. Frontmatter is at the top, so a scan of many
/// skills never pulls whole bodies into memory.
fn read_head(path: &Path, limit: usize) -> Option<String> {
    use std::io::Read;
    let meta = std::fs::metadata(path).ok()?;
    if meta.len() > MAX_FILE_SIZE {
        return None;
    }
    let mut file = std::fs::File::open(path).ok()?;
    let mut buf = vec![0u8; limit.min(meta.len() as usize + 1)];
    let n = file.read(&mut buf).ok()?;
    buf.truncate(n);
    // A multi-byte character can straddle the cut; drop the partial tail.
    Some(match String::from_utf8(buf) {
        Ok(s) => s,
        Err(e) => {
            let valid = e.utf8_error().valid_up_to();
            String::from_utf8_lossy(&e.into_bytes()[..valid]).into_owned()
        }
    })
}

/// Scan one level of subdirectories under `root`. Directories without a
/// readable, well-formed `SKILL.md` are skipped rather than reported: a broken
/// file on disk should not take out the whole listing.
pub fn scan_skills(root: &Path) -> Vec<SkillMeta> {
    let entries = match std::fs::read_dir(root) {
        Ok(entries) => entries,
        Err(e) => {
            // Indistinguishable from "no skills installed" to every caller, and
            // one of those callers treats the result as the complete list.
            tracing::error!(
                error = %e,
                "the skills directory could not be read; no skills will be found"
            );
            return Vec::new();
        }
    };
    let canon_root = std::fs::canonicalize(root).unwrap_or_else(|_| root.to_path_buf());

    let mut out = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        // Refuse anything that resolves outside the root, e.g. a symlinked directory.
        if let Ok(canon) = std::fs::canonicalize(&path)
            && !canon.starts_with(&canon_root)
        {
            continue;
        }
        let Some(dir_name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if !is_valid_slug(dir_name) {
            continue;
        }

        let skill_md = path.join(SKILL_FILE);
        if !skill_md.is_file() {
            continue;
        }
        let Some(head) = read_head(&skill_md, FRONTMATTER_SCAN_BYTES) else {
            continue;
        };
        let Some((llm_name, llm_description)) = parse_frontmatter(&head) else {
            continue;
        };
        if !is_valid_slug(&llm_name) {
            continue;
        }

        out.push(SkillMeta {
            dir_name: dir_name.to_string(),
            llm_name,
            llm_description: truncate_description(&llm_description),
            mtime_hash: format!("{:x}", compute_mtime_hash(&[&skill_md])),
        });
    }

    // Deterministic order: this list ends up in the tool schema, which sits at
    // the front of every provider's prompt cache prefix.
    out.sort_by(|a, b| a.dir_name.cmp(&b.dir_name));
    out
}

fn truncate_description(s: &str) -> String {
    let s = s.trim();
    if s.chars().count() <= MAX_DESCRIPTION_LEN {
        return s.to_string();
    }
    let cut: String = s.chars().take(MAX_DESCRIPTION_LEN - 1).collect();
    format!("{cut}…")
}

/// Full body of a skill, frontmatter stripped.
pub fn read_skill_body(root: &Path, dir_name: &str) -> Option<String> {
    let path = skill_dir(root, dir_name)?.join(SKILL_FILE);
    let content = read_file_utf8(&path)?;
    Some(super::project_instructions::strip_frontmatter(&content).to_string())
}

/// Relative paths of bundled resources, so the model can ask for one by name
/// without us shipping their contents up front.
pub fn list_skill_resources(root: &Path, dir_name: &str) -> Vec<String> {
    let Some(dir) = skill_dir(root, dir_name) else {
        return Vec::new();
    };
    let refs = dir.join(REFERENCES_DIR);
    let mut out = Vec::new();
    collect_files(&refs, &refs, &mut out);
    out.sort();
    out
}

fn collect_files(dir: &Path, base: &Path, out: &mut Vec<String>) {
    const MAX_RESOURCES: usize = 100;
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        if out.len() >= MAX_RESOURCES {
            return;
        }
        let path = entry.path();
        if path.is_dir() {
            collect_files(&path, base, out);
        } else if path.is_file()
            && let Ok(rel) = path.strip_prefix(base)
        {
            out.push(format!(
                "{}/{}",
                REFERENCES_DIR,
                rel.to_string_lossy().replace('\\', "/")
            ));
        }
    }
}

/// Read one bundled resource. `rel_path` is untrusted model input, so it is
/// resolved and then checked to still be inside the skill directory.
pub fn read_skill_resource(root: &Path, dir_name: &str, rel_path: &str) -> Result<String, String> {
    let dir = skill_dir(root, dir_name).ok_or_else(|| format!("unknown skill '{dir_name}'"))?;
    if rel_path.contains("..") || Path::new(rel_path).is_absolute() {
        return Err(format!("invalid resource path '{rel_path}'"));
    }

    let target = dir.join(rel_path.replace('\\', "/"));
    let canon_dir = std::fs::canonicalize(&dir).map_err(|e| e.to_string())?;
    let canon_target =
        std::fs::canonicalize(&target).map_err(|_| format!("resource '{rel_path}' not found in skill '{dir_name}'"))?;
    if !canon_target.starts_with(&canon_dir) {
        return Err(format!("invalid resource path '{rel_path}'"));
    }

    read_file_utf8(&canon_target).ok_or_else(|| format!("resource '{rel_path}' is not readable UTF-8 text"))
}

/// Write a skill's `SKILL.md`, composing frontmatter from the structured fields
/// so the file on disk and the index row can never disagree about the name.
pub fn write_skill_file(
    root: &Path,
    dir_name: &str,
    llm_name: &str,
    description: &str,
    body: &str,
) -> Result<(), String> {
    if !is_valid_slug(dir_name) {
        return Err(format!("'{dir_name}' is not a valid skill directory name"));
    }
    if !is_valid_slug(llm_name) {
        return Err(format!(
            "'{llm_name}' is not a valid skill name (lowercase letters, digits and hyphens only)"
        ));
    }
    let description = description.replace(['\r', '\n'], " ");
    let description = description.trim();
    if description.is_empty() {
        return Err("A skill needs a description — it is all the model sees until it loads the skill".to_string());
    }

    let dir = root.join(dir_name);
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    let content = format!(
        "---\nname: {llm_name}\ndescription: {description}\n---\n\n{}\n",
        body.trim()
    );
    std::fs::write(dir.join(SKILL_FILE), content).map_err(|e| e.to_string())
}

/// Remove a skill directory and everything bundled with it.
pub fn delete_skill_dir(root: &Path, dir_name: &str) -> Result<(), String> {
    let dir = skill_dir(root, dir_name).ok_or_else(|| format!("unknown skill '{dir_name}'"))?;
    // Re-check containment: `dir_name` reached us from a command argument.
    let canon_root = std::fs::canonicalize(root).map_err(|e| e.to_string())?;
    let canon_dir = std::fs::canonicalize(&dir).map_err(|e| e.to_string())?;
    if !canon_dir.starts_with(&canon_root) || canon_dir == canon_root {
        return Err(format!("refusing to delete '{dir_name}'"));
    }
    std::fs::remove_dir_all(canon_dir).map_err(|e| e.to_string())
}

fn skill_dir(root: &Path, dir_name: &str) -> Option<PathBuf> {
    if !is_valid_slug(dir_name) {
        return None;
    }
    let dir = root.join(dir_name);
    dir.is_dir().then_some(dir)
}

/// Reconcile the index with what is actually on disk. The filesystem wins:
/// directories that vanished lose their rows (and, by cascade, their bindings).
pub fn sync_index(conn: &mut SqliteConnection, root: &Path) -> Result<Vec<SkillRow>, String> {
    let found = scan_skills(root);
    let now = now_ms();

    for meta in &found {
        let source = if crate::agent::is_builtin_skill_dir(&meta.dir_name) {
            "official"
        } else {
            "user"
        };
        let is_builtin = i32::from(source == "official");
        // Display fields default to the LLM-facing ones on first sight; the user
        // can rename them afterwards without a rescan clobbering the change.
        let existing = db::ops::skill::get_skill(conn, &meta.dir_name).ok();
        let display_name = existing
            .as_ref()
            .map(|s| s.display_name.clone())
            .unwrap_or_else(|| meta.llm_name.clone());
        let display_description = existing.as_ref().and_then(|s| s.display_description.clone());

        db::ops::skill::upsert_skill(
            conn,
            &SkillInsert {
                dir_name: &meta.dir_name,
                llm_name: &meta.llm_name,
                llm_description: &meta.llm_description,
                display_name: &display_name,
                display_description: display_description.as_deref(),
                source,
                is_enabled: 1,
                is_builtin,
                mtime_hash: Some(&meta.mtime_hash),
                created_at: now,
                updated_at: now,
            },
        )
        .map_err(|e| e.to_string())?;
    }

    // A directory that cannot be read scans as empty, and `delete_missing` with
    // an empty list deletes every row — taking all bindings with it by cascade.
    // Guarding the destructive half means a transient read failure costs one
    // launch's listing rather than the user's whole skill library.
    if found.is_empty() && std::fs::read_dir(root).is_err() {
        tracing::error!(
            skills_root = %root.display(),
            "skills directory unreadable; keeping the existing index rather than clearing it"
        );
        return db::ops::skill::list_skills(conn).map_err(|e| e.to_string());
    }

    let present: Vec<String> = found.iter().map(|m| m.dir_name.clone()).collect();
    let removed = db::ops::skill::delete_missing(conn, &present).map_err(|e| e.to_string())?;
    if removed > 0 {
        tracing::info!(
            rows_deleted = removed,
            scanned = found.len(),
            "dropped skills that are no longer on disk"
        );
    }
    db::ops::skill::list_skills(conn).map_err(|e| e.to_string())
}

fn autobind_key(dir_name: &str) -> String {
    format!("skills.autobind.{dir_name}")
}

/// Bind each built-in skill globally, once ever.
///
/// Indexing a skill does not make it visible: the model only sees skills that
/// are bound, and with none bound the `load_skill` tool disappears entirely, so
/// an unbound built-in is indistinguishable from one that does not exist.
///
/// The per-skill flag is what makes an unbind stick — the user takes it away,
/// the flag stays set, and the next launch does not put it back. A single global
/// "seeded" flag would instead mean a built-in added in a later version could
/// never seed itself on an existing install.
///
/// Must run after `sync_index`: the binding tables carry a foreign key onto
/// `skills.dir_name`, and that row is what `sync_index` creates.
pub fn seed_builtin_bindings(conn: &mut SqliteConnection) {
    for dir_name in crate::agent::BUILTIN_SKILL_DIRS {
        let key = autobind_key(dir_name);
        let already_seeded = db::ops::preference::get_preference(conn, &key).ok().flatten().is_some();
        if already_seeded {
            continue;
        }
        // The flag is written only once the binding lands, so a bind that failed
        // because indexing did not happen retries on the next launch instead of
        // being skipped for good. Deliberately skips the per-anchor cap that the
        // command layer enforces: two built-ins are not what that limit is for.
        if db::ops::skill_binding::bind(conn, SkillLayer::Global, None, dir_name).is_ok() {
            let _ = db::ops::preference::set_preference(conn, &key, "1", now_ms());
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write_skill(root: &Path, dir: &str, frontmatter: &str, body: &str) {
        let d = root.join(dir);
        std::fs::create_dir_all(&d).unwrap();
        std::fs::write(d.join(SKILL_FILE), format!("{frontmatter}{body}")).unwrap();
    }

    #[test]
    fn parses_name_and_description() {
        let content = "---\nname: pdf-tools\ndescription: Fill and read PDF forms\n---\nBody here";
        assert_eq!(
            parse_frontmatter(content),
            Some(("pdf-tools".into(), "Fill and read PDF forms".into()))
        );
    }

    #[test]
    fn parse_tolerates_quotes_extra_keys_and_crlf() {
        let content = "---\r\nname: \"my-skill\"\r\nversion: 3\r\ndescription: 'Does things'\r\n---\r\nBody";
        assert_eq!(
            parse_frontmatter(content),
            Some(("my-skill".into(), "Does things".into()))
        );
    }

    #[test]
    fn parse_rejects_missing_pieces() {
        assert!(parse_frontmatter("no frontmatter at all").is_none());
        assert!(parse_frontmatter("---\nname: only-name\n---\nbody").is_none());
        assert!(parse_frontmatter("---\ndescription: only desc\n---\nbody").is_none());
        assert!(parse_frontmatter("---\nname: unterminated\n").is_none());
    }

    #[test]
    fn slug_validation_rejects_traversal_and_junk() {
        assert!(is_valid_slug("pdf-tools"));
        assert!(is_valid_slug("a1"));
        assert!(!is_valid_slug(".."));
        assert!(!is_valid_slug("../etc"));
        assert!(!is_valid_slug("Has Caps"));
        assert!(!is_valid_slug("has space"));
        assert!(!is_valid_slug("trailing-"));
        assert!(!is_valid_slug(""));
        assert!(!is_valid_slug(&"x".repeat(65)));
    }

    #[test]
    fn scan_finds_valid_skills_sorted() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write_skill(root, "zebra", "---\nname: zebra\ndescription: Z\n---\n", "body");
        write_skill(root, "alpha", "---\nname: alpha\ndescription: A\n---\n", "body");

        let found = scan_skills(root);
        let names: Vec<&str> = found.iter().map(|s| s.dir_name.as_str()).collect();
        assert_eq!(names, vec!["alpha", "zebra"]);
    }

    #[test]
    fn scan_skips_malformed_without_losing_the_rest() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write_skill(root, "good", "---\nname: good\ndescription: Fine\n---\n", "body");
        write_skill(root, "no-frontmatter", "", "just a body");
        write_skill(root, "bad-name", "---\nname: Not A Slug\ndescription: X\n---\n", "b");
        std::fs::create_dir_all(root.join("empty-dir")).unwrap();
        std::fs::write(root.join("loose.md"), "not a skill").unwrap();

        let found = scan_skills(root);
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].dir_name, "good");
    }

    #[test]
    fn scan_truncates_overlong_descriptions() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let long = "x".repeat(500);
        write_skill(
            root,
            "verbose",
            &format!("---\nname: verbose\ndescription: {long}\n---\n"),
            "b",
        );

        let found = scan_skills(root);
        assert_eq!(found[0].llm_description.chars().count(), MAX_DESCRIPTION_LEN);
        assert!(found[0].llm_description.ends_with('…'));
    }

    #[test]
    fn scan_reads_only_the_head_of_huge_bodies() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let huge = "b".repeat(FRONTMATTER_SCAN_BYTES * 4);
        write_skill(root, "big", "---\nname: big\ndescription: Big one\n---\n", &huge);

        let found = scan_skills(root);
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].llm_description, "Big one");
    }

    #[test]
    fn body_has_frontmatter_stripped() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write_skill(root, "s", "---\nname: s\ndescription: D\n---\n", "# Heading\nContent");

        let body = read_skill_body(root, "s").unwrap();
        assert!(body.contains("# Heading"));
        assert!(!body.contains("description:"));
    }

    #[test]
    fn resources_are_listed_relative_and_sorted() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write_skill(root, "s", "---\nname: s\ndescription: D\n---\n", "b");
        let refs = root.join("s").join(REFERENCES_DIR);
        std::fs::create_dir_all(refs.join("sub")).unwrap();
        std::fs::write(refs.join("b.md"), "B").unwrap();
        std::fs::write(refs.join("a.md"), "A").unwrap();
        std::fs::write(refs.join("sub").join("c.md"), "C").unwrap();

        assert_eq!(
            list_skill_resources(root, "s"),
            vec!["references/a.md", "references/b.md", "references/sub/c.md"]
        );
    }

    #[test]
    fn resource_read_rejects_traversal() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write_skill(root, "s", "---\nname: s\ndescription: D\n---\n", "b");
        std::fs::write(root.join("secret.txt"), "TOP SECRET").unwrap();
        let refs = root.join("s").join(REFERENCES_DIR);
        std::fs::create_dir_all(&refs).unwrap();
        std::fs::write(refs.join("ok.md"), "fine").unwrap();

        assert_eq!(read_skill_resource(root, "s", "references/ok.md").unwrap(), "fine");
        assert!(read_skill_resource(root, "s", "../secret.txt").is_err());
        assert!(read_skill_resource(root, "s", "references/../../secret.txt").is_err());
        assert!(read_skill_resource(root, "..", "references/ok.md").is_err());
    }

    #[test]
    fn written_skill_round_trips_through_the_scanner() {
        let dir = tempfile::tempdir().unwrap();
        write_skill_file(dir.path(), "my-skill", "my-skill", "Does a thing", "# Steps\n1. Go").unwrap();

        let found = scan_skills(dir.path());
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].llm_name, "my-skill");
        assert_eq!(found[0].llm_description, "Does a thing");
        assert!(read_skill_body(dir.path(), "my-skill").unwrap().contains("# Steps"));
    }

    #[test]
    fn write_rejects_bad_names_and_empty_descriptions() {
        let dir = tempfile::tempdir().unwrap();
        assert!(write_skill_file(dir.path(), "..", "ok", "d", "b").is_err());
        assert!(write_skill_file(dir.path(), "ok", "Not A Slug", "d", "b").is_err());
        assert!(write_skill_file(dir.path(), "ok", "ok", "   ", "b").is_err());
    }

    #[test]
    fn multiline_description_cannot_break_out_of_frontmatter() {
        let dir = tempfile::tempdir().unwrap();
        write_skill_file(dir.path(), "s", "s", "line one\n---\nname: evil", "body").unwrap();

        let found = scan_skills(dir.path());
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].llm_name, "s");
        assert!(!found[0].llm_description.contains('\n'));
    }

    #[test]
    fn delete_removes_the_directory_but_refuses_the_root() {
        let dir = tempfile::tempdir().unwrap();
        write_skill_file(dir.path(), "doomed", "doomed", "d", "b").unwrap();

        assert!(delete_skill_dir(dir.path(), "..").is_err());
        assert!(dir.path().join("doomed").exists());

        delete_skill_dir(dir.path(), "doomed").unwrap();
        assert!(!dir.path().join("doomed").exists());
    }

    #[test]
    fn missing_skill_reads_return_none_not_panic() {
        let dir = tempfile::tempdir().unwrap();
        assert!(read_skill_body(dir.path(), "nope").is_none());
        assert!(list_skill_resources(dir.path(), "nope").is_empty());
        assert!(scan_skills(&dir.path().join("does-not-exist")).is_empty());
    }

    use crate::db::models::skill::SkillChangeset;
    use crate::db::test_db;

    #[test]
    fn sync_indexes_disk_and_drops_vanished_skills() {
        let dir = tempfile::tempdir().unwrap();
        write_skill_file(dir.path(), "one", "one", "First", "b").unwrap();
        write_skill_file(dir.path(), "two", "two", "Second", "b").unwrap();

        let pool = test_db();
        let mut conn = pool.get().unwrap();
        let indexed = sync_index(&mut conn, dir.path()).unwrap();
        assert_eq!(indexed.len(), 2);

        delete_skill_dir(dir.path(), "two").unwrap();
        let after = sync_index(&mut conn, dir.path()).unwrap();
        assert_eq!(after.len(), 1);
        assert_eq!(after[0].dir_name, "one");
    }

    /// An unreadable directory scans as empty, and an empty scan used to mean
    /// "delete everything" — one bad launch would take the whole library and,
    /// by cascade, every binding.
    #[test]
    fn an_unreadable_skills_directory_does_not_wipe_the_index() {
        let dir = tempfile::tempdir().unwrap();
        write_skill_file(dir.path(), "one", "one", "First", "b").unwrap();

        let pool = test_db();
        let mut conn = pool.get().unwrap();
        assert_eq!(sync_index(&mut conn, dir.path()).unwrap().len(), 1);

        // Unmounted volume, revoked permissions, a path that moved.
        let gone = dir.path().join("not-here");
        let after = sync_index(&mut conn, &gone).unwrap();

        assert_eq!(after.len(), 1, "the index was cleared by a directory it could not read");
    }

    /// The guard must not overreach: a readable directory that is genuinely
    /// empty still means the skills are gone.
    #[test]
    fn an_empty_but_readable_directory_still_clears_the_index() {
        let dir = tempfile::tempdir().unwrap();
        write_skill_file(dir.path(), "one", "one", "First", "b").unwrap();

        let pool = test_db();
        let mut conn = pool.get().unwrap();
        sync_index(&mut conn, dir.path()).unwrap();

        let empty = tempfile::tempdir().unwrap();
        let after = sync_index(&mut conn, empty.path()).unwrap();

        assert!(after.is_empty(), "{after:?}");
    }

    #[test]
    fn sync_picks_up_edited_descriptions() {
        let dir = tempfile::tempdir().unwrap();
        write_skill_file(dir.path(), "s", "s", "Before", "b").unwrap();

        let pool = test_db();
        let mut conn = pool.get().unwrap();
        sync_index(&mut conn, dir.path()).unwrap();

        write_skill_file(dir.path(), "s", "s", "After", "b").unwrap();
        let after = sync_index(&mut conn, dir.path()).unwrap();
        assert_eq!(after[0].llm_description, "After");
    }

    #[test]
    fn sync_preserves_a_renamed_display_name() {
        let dir = tempfile::tempdir().unwrap();
        write_skill_file(dir.path(), "s", "s", "D", "b").unwrap();

        let pool = test_db();
        let mut conn = pool.get().unwrap();
        sync_index(&mut conn, dir.path()).unwrap();
        db::ops::skill::update_skill(
            &mut conn,
            "s",
            &SkillChangeset {
                display_name: Some("我的技能".into()),
                ..Default::default()
            },
        )
        .unwrap();

        let after = sync_index(&mut conn, dir.path()).unwrap();
        assert_eq!(after[0].display_name, "我的技能");
    }

    #[test]
    fn the_generated_manual_is_marked_builtin() {
        let dir = tempfile::tempdir().unwrap();
        crate::agent::manual::write_manual(dir.path(), &[]).unwrap();

        let pool = test_db();
        let mut conn = pool.get().unwrap();
        let indexed = sync_index(&mut conn, dir.path()).unwrap();

        assert_eq!(indexed.len(), 1);
        assert_eq!(indexed[0].source, "official");
        assert_eq!(indexed[0].is_builtin, 1);
    }

    #[test]
    fn the_diagnostics_skill_is_recognised_as_official_too() {
        let dir = tempfile::tempdir().unwrap();
        crate::agent::diagnostics::write_diagnostics(dir.path()).unwrap();

        let pool = test_db();
        let mut conn = pool.get().unwrap();
        let indexed = sync_index(&mut conn, dir.path()).unwrap();

        assert_eq!(indexed.len(), 1);
        assert_eq!(indexed[0].is_builtin, 1);
    }

    #[test]
    fn built_in_skills_are_bound_on_first_launch() {
        let dir = tempfile::tempdir().unwrap();
        crate::agent::manual::write_manual(dir.path(), &[]).unwrap();
        crate::agent::diagnostics::write_diagnostics(dir.path()).unwrap();

        let pool = test_db();
        let mut conn = pool.get().unwrap();
        sync_index(&mut conn, dir.path()).unwrap();
        seed_builtin_bindings(&mut conn);

        let bound = db::ops::skill_binding::list_layer(&mut conn, SkillLayer::Global, None).unwrap();
        for dir_name in crate::agent::BUILTIN_SKILL_DIRS {
            assert!(bound.iter().any(|b| b == dir_name), "{dir_name} not bound: {bound:?}");
        }
    }

    /// The point of the per-skill flag: seeding is a one-time nudge, not a
    /// policy the app re-enforces on every launch.
    #[test]
    fn unbinding_a_built_in_skill_survives_the_next_launch() {
        let dir = tempfile::tempdir().unwrap();
        crate::agent::diagnostics::write_diagnostics(dir.path()).unwrap();

        let pool = test_db();
        let mut conn = pool.get().unwrap();
        sync_index(&mut conn, dir.path()).unwrap();
        seed_builtin_bindings(&mut conn);

        db::ops::skill_binding::unbind(
            &mut conn,
            SkillLayer::Global,
            None,
            crate::agent::diagnostics::DIAGNOSTICS_DIR,
        )
        .unwrap();

        seed_builtin_bindings(&mut conn);

        let bound = db::ops::skill_binding::list_layer(&mut conn, SkillLayer::Global, None).unwrap();
        assert!(
            !bound.iter().any(|b| b == crate::agent::diagnostics::DIAGNOSTICS_DIR),
            "the skill came back after being unbound: {bound:?}"
        );
    }

    /// A bind that could not land must not burn its flag, or the skill would
    /// never be seeded again.
    #[test]
    fn a_failed_bind_is_retried_on_the_next_launch() {
        let pool = test_db();
        let mut conn = pool.get().unwrap();

        // No sync_index, so there is no skills row for the foreign key.
        seed_builtin_bindings(&mut conn);
        let bound = db::ops::skill_binding::list_layer(&mut conn, SkillLayer::Global, None).unwrap();
        assert!(bound.is_empty(), "{bound:?}");

        let dir = tempfile::tempdir().unwrap();
        crate::agent::diagnostics::write_diagnostics(dir.path()).unwrap();
        sync_index(&mut conn, dir.path()).unwrap();
        seed_builtin_bindings(&mut conn);

        let bound = db::ops::skill_binding::list_layer(&mut conn, SkillLayer::Global, None).unwrap();
        assert!(
            bound.iter().any(|b| b == crate::agent::diagnostics::DIAGNOSTICS_DIR),
            "{bound:?}"
        );
    }
}
