//! The schema as the 65 Diesel migrations left it, as one SeaORM migration.
//!
//! GENERATED by `cargo run -p meridian-core --example gen_baseline --features test-support`
//! from a database those migrations produced; do not edit by hand. The
//! equivalence tests in `db/sea/equivalence_tests.rs` compare what this builds
//! with what replaying the migrations builds, table by table.
//!
//! Column types are the declared ones: `BIGINT` is `big_int`, `INTEGER` is
//! `integer`, and both render as `integer` on SQLite, where the distinction is
//! one of affinity only. `CHECK` expressions, the `WHERE` of a partial index
//! and the three triggers are SQLite text, passed through — see the
//! `backend: sqlite-only` notes in `migration/mod.rs`.

use sea_orm::sea_query::ForeignKeyAction::{Cascade, NoAction, Restrict, SetNull};
use sea_orm::sea_query::IndexOrder::{Asc, Desc};

use super::{Object, big_int, check, double, fk, index, integer, key, render_sqlite, t, table, text, trigger, unique};

/// The statements SQLite runs for the baseline, in order.
pub fn sqlite_statements() -> Vec<String> {
    render_sqlite(&objects())
}

#[rustfmt::skip]
pub(super) fn objects() -> Vec<Object> {
    vec![
        t(table("providers")
            .col(text("id").not_null().primary_key())
            .col(text("name").not_null())
            .col(text("provider_type").not_null().default("openai"))
            .col(text("base_url").not_null())
            .col(integer("is_enabled").not_null().default(1i64))
            .col(integer("sort_order").not_null().default(0i64))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .col(text("api_format").not_null().default("chat_completions"))
            .col(text("catalog_id"))
            .col(text("credential_kind").not_null().default("api_key"))
            .col(text("transport_profile").not_null().default("standard"))
            .col(text("icon"))
            .col(integer("codex_request_shape").not_null().default(0i64))
        ),
        t(table("assistants")
            .col(text("id").not_null().primary_key())
            .col(text("name").not_null())
            .col(text("description"))
            .col(text("avatar"))
            .col(text("system_prompt").not_null().default(""))
            .col(text("provider_id"))
            .col(text("model_id"))
            .col(double("temperature"))
            .col(double("top_p"))
            .col(integer("max_tokens"))
            .col(integer("is_default").not_null().default(0i64))
            .col(integer("sort_order").not_null().default(0i64))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .col(integer("context_limit").not_null().default(128000i64))
            .col(integer("compact_keep_recent").not_null().default(10i64))
            .col(text("enabled_tools"))
            .col(integer("thinking_enabled").not_null().default(0i64))
            .col(integer("thinking_budget"))
            .col(text("tool_preset_id"))
            .col(integer("auto_compact_enabled").not_null().default(0i64))
            .foreign_key(&mut fk(&["tool_preset_id"], "tool_presets", &["id"], SetNull))
            .foreign_key(&mut fk(&["provider_id"], "providers", &["id"], SetNull))
        ),
        t(table("conversations")
            .col(text("id").not_null().primary_key())
            .col(text("title"))
            .col(text("assistant_id"))
            .col(integer("is_pinned").not_null().default(0i64))
            .col(integer("is_archived").not_null().default(0i64))
            .col(integer("message_count").not_null().default(0i64))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .col(text("project_id"))
            .col(text("thinking_level"))
            .col(integer("fast_mode").not_null().default(0i64))
            .col(text("mode"))
            .col(text("head_message_id"))
            .col(integer("accept_edits").not_null().default(0i64))
            .col(text("parent_conversation_id"))
            .col(text("spawned_by_message_id"))
            .col(text("spawned_by_call_id"))
            .col(text("spawned_turn_id"))
            .col(text("agent_kind"))
            .col(text("agent_provider_id"))
            .col(text("agent_model_id"))
            .foreign_key(&mut fk(&["head_message_id"], "messages", &["id"], SetNull))
            .foreign_key(&mut fk(&["project_id"], "projects", &["id"], SetNull))
            .foreign_key(&mut fk(&["assistant_id"], "assistants", &["id"], SetNull))
        ),
        t(table("messages")
            .col(text("id").not_null().primary_key())
            .col(text("conversation_id").not_null())
            .col(text("role").not_null())
            .col(text("content").not_null().default(""))
            .col(text("provider_id"))
            .col(text("model_id"))
            .col(integer("input_tokens"))
            .col(integer("output_tokens"))
            .col(text("tool_calls"))
            .col(text("tool_call_id"))
            .col(integer("sort_order").not_null().default(0i64))
            .col(big_int("created_at").not_null())
            .col(text("reasoning_content"))
            .col(integer("rating"))
            .col(integer("schema_version").not_null().default(1i64))
            .col(integer("is_compact_summary").not_null().default(0i64))
            .col(big_int("sender_id"))
            .col(text("parent_id"))
            .col(text("compact_anchor_id"))
            .col(text("source"))
            .col(text("turn_id"))
            .col(text("tool_outcome"))
            .col(integer("cache_read_tokens"))
            .col(integer("cache_write_tokens"))
            .col(text("provider_name"))
            .col(text("provider_state"))
            .col(text("auto_review"))
            .col(integer("server_tool_calls"))
            .col(text("tool_diffs"))
            .col(text("response_model_id"))
            .foreign_key(&mut fk(&["compact_anchor_id"], "messages", &["id"], Cascade))
            .foreign_key(&mut fk(&["provider_id"], "providers", &["id"], SetNull))
            .foreign_key(&mut fk(&["conversation_id"], "conversations", &["id"], Cascade))
        ),
        t(table("preferences")
            .col(text("key").not_null().primary_key())
            .col(text("value").not_null())
            .col(big_int("updated_at").not_null())
        ),
        t(table("emoji_packs")
            .col(text("id").not_null().primary_key())
            .col(text("name").not_null())
            .col(text("description"))
            .col(text("cover_image"))
            .col(integer("is_builtin").not_null().default(0i64))
            .col(integer("sort_order").not_null().default(0i64))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .col(text("kind").not_null().default("manual"))
            .col(text("source_account_id"))
        ),
        t(table("emojis")
            .col(text("id").not_null().primary_key())
            .col(text("pack_id").not_null())
            .col(text("name").not_null())
            .col(text("tags"))
            .col(text("file_name").not_null())
            .col(text("file_format").not_null().default("gif"))
            .col(integer("sort_order").not_null().default(0i64))
            .col(big_int("created_at").not_null())
            .col(text("source").not_null().default("local"))
            .col(text("source_key"))
            .col(text("native_payload"))
            .col(text("semantic_status").not_null().default("confirmed"))
            .col(text("suggested_name"))
            .col(text("suggested_tags"))
            .col(big_int("file_size").not_null().default(0i64))
            .col(integer("seen_count").not_null().default(1i64))
            .col(big_int("last_seen_at"))
            .foreign_key(&mut fk(&["pack_id"], "emoji_packs", &["id"], Cascade))
        ),
        t(table("assistant_emoji_packs")
            .col(text("assistant_id").not_null())
            .col(text("pack_id").not_null())
            .col(big_int("created_at").not_null())
            .primary_key(&mut key(&["assistant_id", "pack_id"]))
            .foreign_key(&mut fk(&["pack_id"], "emoji_packs", &["id"], Cascade))
            .foreign_key(&mut fk(&["assistant_id"], "assistants", &["id"], Cascade))
        ),
        t(table("tool_categories")
            .col(text("id").not_null().primary_key())
            .col(text("name").not_null())
            .col(text("description"))
            .col(text("icon"))
            .col(integer("sort_order").not_null().default(0i64))
            .col(big_int("created_at").not_null())
        ),
        t(table("custom_tools")
            .col(text("id").not_null().primary_key())
            .col(text("name").not_null())
            .col(text("description").not_null())
            .col(text("category_id"))
            .col(text("parameters_schema").not_null().default("{\"type\":\"object\",\"properties\":{}}"))
            .col(text("command").not_null())
            .col(text("args_template"))
            .col(text("working_directory"))
            .col(integer("timeout_ms").default(30000i64))
            .col(text("permission").not_null().default("ask"))
            .col(integer("is_enabled").not_null().default(1i64))
            .col(integer("sort_order").not_null().default(0i64))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .index(&mut unique(&["name"]))
            .foreign_key(&mut fk(&["category_id"], "tool_categories", &["id"], SetNull))
        ),
        t(table("tool_presets")
            .col(text("id").not_null().primary_key())
            .col(text("name").not_null())
            .col(text("description"))
            .col(text("icon"))
            .col(text("tool_names").not_null())
            .col(integer("is_builtin").not_null().default(0i64))
            .col(integer("sort_order").not_null().default(0i64))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
        ),
        t(table("projects")
            .col(text("id").not_null().primary_key())
            .col(text("name").not_null())
            .col(text("path"))
            .col(text("source_type").not_null().default("local"))
            .col(text("source_id"))
            .col(text("assistant_id"))
            .col(text("description"))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .foreign_key(&mut fk(&["assistant_id"], "assistants", &["id"], SetNull))
        ),
        t(table("cached_models")
            .col(integer("id").primary_key().auto_increment())
            .col(text("provider_id").not_null())
            .col(text("model_id").not_null())
            .col(text("model_name").not_null())
            .col(big_int("fetched_at").not_null())
            .foreign_key(&mut fk(&["provider_id"], "providers", &["id"], Cascade))
        ),
        t(table("skills")
            .col(text("dir_name").primary_key())
            .col(text("llm_name").not_null())
            .col(text("llm_description").not_null())
            .col(text("display_name").not_null())
            .col(text("display_description"))
            .col(text("source").not_null().default("user"))
            .col(integer("is_enabled").not_null().default(1i64))
            .col(integer("is_builtin").not_null().default(0i64))
            .col(text("mtime_hash"))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
        ),
        t(table("skill_bindings_global")
            .col(text("dir_name").primary_key())
            .foreign_key(&mut fk(&["dir_name"], "skills", &["dir_name"], Cascade))
        ),
        t(table("skill_bindings_project")
            .col(text("project_id").not_null())
            .col(text("dir_name").not_null())
            .primary_key(&mut key(&["project_id", "dir_name"]))
            .foreign_key(&mut fk(&["dir_name"], "skills", &["dir_name"], Cascade))
            .foreign_key(&mut fk(&["project_id"], "projects", &["id"], Cascade))
        ),
        t(table("skill_bindings_assistant")
            .col(text("assistant_id").not_null())
            .col(text("dir_name").not_null())
            .primary_key(&mut key(&["assistant_id", "dir_name"]))
            .foreign_key(&mut fk(&["dir_name"], "skills", &["dir_name"], Cascade))
            .foreign_key(&mut fk(&["assistant_id"], "assistants", &["id"], Cascade))
        ),
        t(table("todo_lists")
            .col(text("id").not_null().primary_key())
            .col(text("conversation_id").not_null())
            .col(text("title").not_null())
            .col(text("status").not_null().default("in_progress"))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .foreign_key(&mut fk(&["conversation_id"], "conversations", &["id"], Cascade))
        ),
        t(table("todo_items")
            .col(text("id").not_null().primary_key())
            .col(text("list_id").not_null())
            .col(text("content").not_null())
            .col(text("active_form").not_null())
            .col(text("status").not_null().default("pending"))
            .col(integer("sort_order").not_null().default(0i64))
            .col(big_int("created_at").not_null())
            .foreign_key(&mut fk(&["list_id"], "todo_lists", &["id"], Cascade))
        ),
        t(table("memories")
            .col(text("id").not_null().primary_key())
            .col(text("scope_type").not_null())
            .col(text("scope_id").not_null())
            .col(text("key").not_null())
            .col(text("content").not_null())
            .col(text("memory_type").not_null().default("general"))
            .col(text("subject_scope_id"))
            .col(text("origin").not_null().default("desktop"))
            .col(text("visibility").not_null().default("normal"))
            .col(text("source_session_id"))
            .col(big_int("deleted_at"))
            .col(text("deleted_by"))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
        ),
        t(table("memory_subjects")
            .col(text("scope_id").not_null().primary_key())
            .col(text("display_name"))
            .col(big_int("last_seen_at").not_null())
            .col(big_int("created_at").not_null())
            .col(integer("is_protected").not_null().default(0i64))
            .col(integer("is_pinned").not_null().default(0i64))
            .col(integer("opted_out").not_null().default(0i64))
        ),
        t(table("memory_proposals")
            .col(integer("id").primary_key().auto_increment())
            .col(text("key").not_null())
            .col(text("content").not_null())
            .col(text("memory_type").not_null().default("general"))
            .col(text("origin_session"))
            .col(big_int("proposer_id"))
            .col(text("status").not_null().default("pending"))
            .col(big_int("created_at").not_null())
            .col(big_int("expires_at").not_null())
            .col(big_int("resolved_at"))
            .col(big_int("resolved_by"))
        ),
        t(table("mode_artifacts")
            .col(text("id").not_null().primary_key())
            .col(text("conversation_id").not_null())
            .col(text("kind").not_null().default("plan"))
            .col(text("content").not_null())
            .col(text("status").not_null())
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .foreign_key(&mut fk(&["conversation_id"], "conversations", &["id"], Cascade))
        ),
        t(table("mcp_servers")
            .col(text("id").not_null().primary_key())
            .col(text("name").not_null())
            .col(text("transport_type").not_null().default("stdio"))
            .col(text("command"))
            .col(text("args"))
            .col(text("env"))
            .col(text("url"))
            .col(text("headers"))
            .col(integer("is_enabled").not_null().default(0i64))
            .col(integer("sort_order").not_null().default(0i64))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
        ),
        t(table("turns")
            .col(text("id").not_null().primary_key())
            .col(text("conversation_id").not_null())
            .col(text("origin").not_null())
            .col(text("status").not_null())
            .col(text("phase"))
            .col(text("phase_tool"))
            .col(text("error"))
            .col(big_int("started_at").not_null())
            .col(big_int("updated_at").not_null())
            .col(big_int("ended_at"))
            .col(big_int("reported_at"))
            .col(big_int("parent_reported_at"))
            .col(big_int("self_id"))
            .col(text("trigger").not_null().default("user"))
            .col(text("trigger_ref"))
            .foreign_key(&mut fk(&["conversation_id"], "conversations", &["id"], Cascade))
            .check(check(r"trigger IN ('user', 'plan_continuation', 'task_completion', 'agent_autonomous')"))
        ),
        t(table("message_stickers")
            .col(text("message_id").not_null())
            .col(text("sticker_id").not_null())
            .col(integer("position").not_null().default(0i64))
            .primary_key(&mut key(&["message_id", "position"]))
            .foreign_key(&mut fk(&["sticker_id"], "emojis", &["id"], Restrict))
            .foreign_key(&mut fk(&["message_id"], "messages", &["id"], Cascade))
        ),
        t(table("queued_prompts")
            .col(text("id").not_null().primary_key())
            .col(text("conversation_id").not_null())
            .col(text("content").not_null())
            .col(text("delivery").not_null())
            .col(integer("position").not_null())
            .col(big_int("created_at").not_null())
            .col(big_int("dispatched_at"))
            .col(text("dispatched_turn_id"))
            .col(big_int("settled_at"))
            .col(text("settled_message_id"))
            .col(big_int("held_at"))
            .col(big_int("reported_at"))
            .foreign_key(&mut fk(&["conversation_id"], "conversations", &["id"], Cascade))
        ),
        t(table("acp_sessions")
            .col(text("conversation_id").not_null().primary_key())
            .col(text("acp_session_id"))
            .col(text("cwd").not_null())
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .foreign_key(&mut fk(&["conversation_id"], "conversations", &["id"], Cascade))
        ),
        t(table("voice_blobs")
            .col(text("id").not_null().primary_key())
            .col(big_int("bot_self_id").not_null())
            .col(text("source_type").not_null())
            .col(text("source_id").not_null())
            .col(text("sha256").not_null())
            .col(text("file_format").not_null())
            .col(text("file_name").not_null())
            .col(big_int("file_size").not_null())
            .col(text("status").not_null().default("pending"))
            .col(text("owner_token"))
            .col(big_int("fence_epoch").not_null().default(0i64))
            .col(big_int("lease_expires_at"))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .check(check(r"status IN ('pending', 'ready', 'damaged', 'deleting')"))
            .check(check(r"(status =  'pending' AND owner_token IS NOT NULL AND lease_expires_at IS NOT NULL) OR
    (status <> 'pending' AND owner_token IS     NULL AND lease_expires_at IS     NULL)"))
        ),
        t(table("voice_clips")
            .col(text("id").not_null().primary_key())
            .col(text("blob_id").not_null())
            .col(big_int("bot_self_id").not_null())
            .col(text("source_type").not_null())
            .col(text("source_id").not_null())
            .col(text("sender_id").not_null())
            .col(big_int("platform_message_id"))
            .col(integer("segment_index").not_null().default(0i64))
            .col(text("transcript"))
            .col(text("transcript_source"))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .foreign_key(&mut fk(&["blob_id"], "voice_blobs", &["id"], Cascade))
            .check(check(r"(transcript IS NULL AND transcript_source IS NULL) OR
    (transcript IS NOT NULL AND transcript_source IS NOT NULL)"))
        ),
        t(table("voice_sender_optouts")
            .col(text("sender_id").not_null().primary_key())
            .col(big_int("created_at").not_null())
        ),
        t(table("journal_files")
            .col(text("id").not_null().primary_key())
            .col(text("norm_path").not_null())
            .col(text("display_path").not_null())
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
        ),
        t(table("journal_blobs")
            .col(text("sha256").not_null().primary_key())
            .col(big_int("byte_len").not_null())
            .col(integer("line_count").not_null())
            .col(big_int("created_at").not_null())
        ),
        t(table("journal_versions")
            .col(text("id").not_null().primary_key())
            .col(text("file_id").not_null())
            .col(big_int("seq").not_null())
            .col(text("op").not_null())
            .col(text("observed_old_sha"))
            .col(text("new_sha"))
            .col(text("source").not_null())
            .col(text("conversation_id"))
            .col(text("turn_id"))
            .col(text("project_id"))
            .col(text("origin"))
            .col(text("model_id"))
            .col(text("tool_name"))
            .col(text("moved_from_version_id"))
            .col(big_int("created_at").not_null())
            .foreign_key(&mut fk(&["new_sha"], "journal_blobs", &["sha256"], NoAction))
            .foreign_key(&mut fk(&["observed_old_sha"], "journal_blobs", &["sha256"], NoAction))
            .foreign_key(&mut fk(&["file_id"], "journal_files", &["id"], Cascade))
            .check(check(r"op IN (
            'write', 'edit', 'patch', 'delete', 'rename_from', 'rename_to',
            'command_observed', 'external', 'rewind'
        )"))
            .check(check(r"source IN ('native', 'hosted', 'inferred', 'external', 'rewind')"))
            .check(check(r"source <> 'external' OR conversation_id IS NULL"))
        ),
        t(table("acp_context_deliveries")
            .col(text("context_item_id").not_null().primary_key())
            .col(big_int("delivered_at").not_null())
            .foreign_key(&mut fk(&["context_item_id"], "message_context_items", &["id"], Cascade))
        ),
        t(table("audit_messages")
            .col(text("id").not_null().primary_key())
            .col(big_int("recorded_at").not_null())
            .col(text("message_id").not_null())
            .col(text("conversation_id").not_null())
            .col(text("turn_id"))
            .col(text("source_type"))
            .col(text("source_id"))
            .col(text("turn_origin"))
            .col(text("role").not_null())
            .col(text("content").not_null())
            .col(big_int("sender_id"))
            .col(text("sender_name"))
            .col(text("provider_id"))
            .col(text("provider_name"))
            .col(text("model_id"))
            .col(integer("input_tokens"))
            .col(integer("output_tokens"))
            .col(integer("cache_read_tokens"))
            .col(integer("cache_write_tokens"))
            .col(big_int("created_at").not_null())
            .col(text("input_price"))
            .col(text("output_price"))
            .col(text("cache_read_price"))
            .col(text("cache_write_price"))
            .col(big_int("self_id"))
            .col(integer("server_tool_calls"))
            .col(text("server_tool_price"))
            .col(text("billing_mode").not_null().default("metered"))
            .col(text("response_model_id"))
            .check(check(r"input_price IS NULL OR input_price = '0' OR (
        typeof(input_price) = 'text'
        AND length(input_price) > 0 AND input_price NOT GLOB '*[^0-9.]*' AND input_price NOT LIKE '%.%.%'
        AND (substr(input_price, 1, 1) <> '0' OR substr(input_price, 2, 1) = '.')
        AND (instr(input_price, '.') = 0 OR (instr(input_price, '.') BETWEEN 2 AND length(input_price) - 1 AND substr(input_price, -1, 1) GLOB '[1-9]'))
        AND length(CASE WHEN instr(input_price, '.') = 0 THEN input_price ELSE substr(input_price, 1, instr(input_price, '.') - 1) END) <= 20
        AND (instr(input_price, '.') = 0 OR length(input_price) - instr(input_price, '.') <= 18)
    )"))
            .check(check(r"output_price IS NULL OR output_price = '0' OR (
        typeof(output_price) = 'text'
        AND length(output_price) > 0 AND output_price NOT GLOB '*[^0-9.]*' AND output_price NOT LIKE '%.%.%'
        AND (substr(output_price, 1, 1) <> '0' OR substr(output_price, 2, 1) = '.')
        AND (instr(output_price, '.') = 0 OR (instr(output_price, '.') BETWEEN 2 AND length(output_price) - 1 AND substr(output_price, -1, 1) GLOB '[1-9]'))
        AND length(CASE WHEN instr(output_price, '.') = 0 THEN output_price ELSE substr(output_price, 1, instr(output_price, '.') - 1) END) <= 20
        AND (instr(output_price, '.') = 0 OR length(output_price) - instr(output_price, '.') <= 18)
    )"))
            .check(check(r"cache_read_price IS NULL OR cache_read_price = '0' OR (
        typeof(cache_read_price) = 'text'
        AND length(cache_read_price) > 0 AND cache_read_price NOT GLOB '*[^0-9.]*' AND cache_read_price NOT LIKE '%.%.%'
        AND (substr(cache_read_price, 1, 1) <> '0' OR substr(cache_read_price, 2, 1) = '.')
        AND (instr(cache_read_price, '.') = 0 OR (instr(cache_read_price, '.') BETWEEN 2 AND length(cache_read_price) - 1 AND substr(cache_read_price, -1, 1) GLOB '[1-9]'))
        AND length(CASE WHEN instr(cache_read_price, '.') = 0 THEN cache_read_price ELSE substr(cache_read_price, 1, instr(cache_read_price, '.') - 1) END) <= 20
        AND (instr(cache_read_price, '.') = 0 OR length(cache_read_price) - instr(cache_read_price, '.') <= 18)
    )"))
            .check(check(r"cache_write_price IS NULL OR cache_write_price = '0' OR (
        typeof(cache_write_price) = 'text'
        AND length(cache_write_price) > 0 AND cache_write_price NOT GLOB '*[^0-9.]*' AND cache_write_price NOT LIKE '%.%.%'
        AND (substr(cache_write_price, 1, 1) <> '0' OR substr(cache_write_price, 2, 1) = '.')
        AND (instr(cache_write_price, '.') = 0 OR (instr(cache_write_price, '.') BETWEEN 2 AND length(cache_write_price) - 1 AND substr(cache_write_price, -1, 1) GLOB '[1-9]'))
        AND length(CASE WHEN instr(cache_write_price, '.') = 0 THEN cache_write_price ELSE substr(cache_write_price, 1, instr(cache_write_price, '.') - 1) END) <= 20
        AND (instr(cache_write_price, '.') = 0 OR length(cache_write_price) - instr(cache_write_price, '.') <= 18)
    )"))
            .check(check(r"server_tool_price IS NULL OR server_tool_price = '0' OR (
        typeof(server_tool_price) = 'text'
        AND length(server_tool_price) > 0 AND server_tool_price NOT GLOB '*[^0-9.]*' AND server_tool_price NOT LIKE '%.%.%'
        AND (substr(server_tool_price, 1, 1) <> '0' OR substr(server_tool_price, 2, 1) = '.')
        AND (instr(server_tool_price, '.') = 0 OR (instr(server_tool_price, '.') BETWEEN 2 AND length(server_tool_price) - 1 AND substr(server_tool_price, -1, 1) GLOB '[1-9]'))
        AND length(CASE WHEN instr(server_tool_price, '.') = 0 THEN server_tool_price ELSE substr(server_tool_price, 1, instr(server_tool_price, '.') - 1) END) <= 20
        AND (instr(server_tool_price, '.') = 0 OR length(server_tool_price) - instr(server_tool_price, '.') <= 18)
    )"))
            .check(check(r"billing_mode IN ('metered', 'subscription', 'external')"))
        ),
        t(table("plan_documents")
            .col(text("id").not_null().primary_key())
            .col(text("conversation_id").not_null())
            .col(text("state").not_null())
            .col(text("head_revision_id"))
            .col(text("approved_revision_id"))
            .col(big_int("working_generation").not_null().default(0i64))
            .col(text("file_rel_path").not_null())
            .col(big_int("lock_version").not_null().default(0i64))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .foreign_key(&mut fk(&["conversation_id"], "conversations", &["id"], Cascade))
            .check(check(r"state IN ('drafting', 'reviewing', 'approved', 'done')"))
            .check(check(r"working_generation >= 0"))
            .check(check(r"lock_version >= 0"))
        ),
        t(table("plan_revisions")
            .col(text("id").not_null().primary_key())
            .col(text("document_id").not_null())
            .col(big_int("revision_no").not_null())
            .col(text("parent_revision_id"))
            .col(text("author_kind").not_null())
            .col(text("content_markdown").not_null())
            .col(text("content_sha256").not_null())
            .col(text("patch"))
            .col(text("source_message_id"))
            .col(text("source_call_id"))
            .col(text("responding_to_suggestion_revision_id"))
            .col(text("editor_json"))
            .col(integer("editor_schema_version"))
            .col(text("editor_schema_hash"))
            .col(text("legacy_source_artifact_id"))
            .col(big_int("created_at").not_null())
            .index(&mut unique(&["document_id", "revision_no"]))
            .index(&mut unique(&["legacy_source_artifact_id"]))
            .foreign_key(&mut fk(&["document_id"], "plan_documents", &["id"], Cascade))
            .check(check(r"revision_no > 0"))
            .check(check(r"author_kind IN ('assistant', 'user_suggestion', 'legacy')"))
            .check(check(r"length(content_sha256) = 64 AND content_sha256 NOT GLOB '*[^0-9a-f]*'"))
            .check(check(r"editor_json IS NULL OR json_valid(editor_json)"))
        ),
        t(table("plan_review_sessions")
            .col(text("id").not_null().primary_key())
            .col(text("document_id").not_null())
            .col(text("submitted_revision_id").not_null())
            .col(text("turn_id"))
            .col(text("assistant_message_id"))
            .col(text("provider_call_id"))
            .col(text("provider_kind").not_null())
            .col(text("native_runtime_config_json"))
            .col(text("state").not_null())
            .col(text("decision_id"))
            .col(text("decision_summary"))
            .col(text("suggestion_revision_id"))
            .col(big_int("lock_version").not_null().default(0i64))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .col(big_int("decided_at"))
            .index(&mut unique(&["decision_id"]))
            .foreign_key(&mut fk(&["submitted_revision_id"], "plan_revisions", &["id"], Cascade))
            .foreign_key(&mut fk(&["document_id"], "plan_documents", &["id"], Cascade))
            .check(check(r"provider_kind IN ('native', 'acp', 'legacy')"))
            .check(check(r"native_runtime_config_json IS NULL OR json_valid(native_runtime_config_json)"))
            .check(check(r"state IN ('pending', 'approved', 'changes_requested', 'orphaned')"))
            .check(check(r"lock_version >= 0"))
        ),
        t(table("plan_review_drafts")
            .col(text("review_id").not_null().primary_key())
            .col(text("base_revision_id").not_null())
            .col(big_int("generation").not_null().default(0i64))
            .col(text("mode").not_null())
            .col(text("base_editor_json"))
            .col(text("draft_editor_json"))
            .col(text("base_normalized_markdown").not_null())
            .col(text("draft_normalized_markdown").not_null())
            .col(text("source_text"))
            .col(integer("editor_schema_version"))
            .col(text("editor_schema_hash"))
            .col(text("global_note"))
            .col(text("selection_json"))
            .col(text("draft_sha256").not_null())
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .foreign_key(&mut fk(&["base_revision_id"], "plan_revisions", &["id"], Cascade))
            .foreign_key(&mut fk(&["review_id"], "plan_review_sessions", &["id"], Cascade))
            .check(check(r"generation >= 0"))
            .check(check(r"mode IN ('rich', 'source')"))
            .check(check(r"base_editor_json IS NULL OR json_valid(base_editor_json)"))
            .check(check(r"draft_editor_json IS NULL OR json_valid(draft_editor_json)"))
            .check(check(r"selection_json IS NULL OR json_valid(selection_json)"))
            .check(check(r"length(draft_sha256) = 64 AND draft_sha256 NOT GLOB '*[^0-9a-f]*'"))
            .check(check(r"(mode = 'rich' AND source_text IS NULL) OR
    (mode = 'source' AND source_text IS NOT NULL)"))
        ),
        t(table("plan_comments")
            .col(text("id").not_null().primary_key())
            .col(text("review_id").not_null())
            .col(integer("position").not_null())
            .col(text("state").not_null())
            .col(text("anchor_kind").not_null())
            .col(text("anchor_json").not_null())
            .col(text("body").not_null())
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .index(&mut unique(&["review_id", "position"]))
            .foreign_key(&mut fk(&["review_id"], "plan_review_sessions", &["id"], Cascade))
            .check(check(r"position >= 0"))
            .check(check(r"state IN ('draft', 'active', 'orphaned', 'submitted', 'deleted')"))
            .check(check(r"anchor_kind IN ('rich', 'source')"))
            .check(check(r"json_valid(anchor_json)"))
        ),
        t(table("plan_review_deliveries")
            .col(text("id").not_null().primary_key())
            .col(text("review_id").not_null())
            .col(text("target").not_null())
            .col(text("state").not_null())
            .col(text("payload_json").not_null())
            .col(text("attempt_token"))
            .col(text("target_session_id"))
            .col(text("target_turn_id"))
            .col(text("error"))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .col(big_int("dispatched_at"))
            .col(big_int("acknowledged_at"))
            .col(big_int("held_at"))
            .index(&mut unique(&["review_id", "target"]))
            .foreign_key(&mut fk(&["review_id"], "plan_review_sessions", &["id"], Cascade))
            .check(check(r"target IN ('native', 'acp')"))
            .check(check(r"state IN ('queued', 'dispatched', 'acknowledged', 'held', 'in_doubt')"))
            .check(check(r"json_valid(payload_json)"))
        ),
        t(table("plan_materializations")
            .col(text("id").not_null().primary_key())
            .col(text("document_id").not_null())
            .col(text("revision_id").not_null())
            .col(big_int("generation").not_null())
            .col(text("expected_sha256"))
            .col(text("desired_sha256").not_null())
            .col(text("state").not_null())
            .col(integer("force_replace").not_null().default(0i64))
            .col(text("error"))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .col(big_int("applied_at"))
            .index(&mut unique(&["document_id", "generation"]))
            .foreign_key(&mut fk(&["revision_id"], "plan_revisions", &["id"], Cascade))
            .foreign_key(&mut fk(&["document_id"], "plan_documents", &["id"], Cascade))
            .check(check(r"generation > 0"))
            .check(check(r"expected_sha256 IS NULL OR
    (length(expected_sha256) = 64 AND expected_sha256 NOT GLOB '*[^0-9a-f]*')"))
            .check(check(r"length(desired_sha256) = 64 AND desired_sha256 NOT GLOB '*[^0-9a-f]*'"))
            .check(check(r"state IN ('pending', 'applied', 'conflict')"))
            .check(check(r"force_replace IN (0, 1)"))
        ),
        t(table("message_context_items")
            .col(text("id").not_null().primary_key())
            .col(text("message_id").not_null())
            .col(integer("position").not_null())
            .col(text("kind").not_null())
            .col(text("content").not_null())
            .col(text("display_path"))
            .col(integer("line_start"))
            .col(integer("line_end"))
            .col(text("content_hash").not_null())
            .col(integer("byte_count").not_null())
            .col(integer("line_count").not_null())
            .col(integer("token_count").not_null())
            .col(integer("truncated").not_null().default(0i64))
            .col(text("metadata"))
            .col(big_int("created_at").not_null())
            .index(&mut unique(&["message_id", "position"]))
            .foreign_key(&mut fk(&["message_id"], "messages", &["id"], Cascade))
            .check(check(r"kind IN ('project_file', 'project_directory', 'shell_output', 'conversation')"))
            .check(check(r"truncated IN (0, 1)"))
            .check(check(r"(line_start IS NULL AND line_end IS NULL)
    OR (line_start > 0 AND line_end >= line_start)"))
        ),
        t(table("queued_prompt_context_items")
            .col(text("id").not_null().primary_key())
            .col(text("queue_id").not_null())
            .col(integer("position").not_null())
            .col(text("kind").not_null())
            .col(text("content").not_null())
            .col(text("display_path"))
            .col(integer("line_start"))
            .col(integer("line_end"))
            .col(text("content_hash").not_null())
            .col(integer("byte_count").not_null())
            .col(integer("line_count").not_null())
            .col(integer("token_count").not_null())
            .col(integer("truncated").not_null().default(0i64))
            .col(text("metadata"))
            .col(big_int("created_at").not_null())
            .index(&mut unique(&["queue_id", "position"]))
            .foreign_key(&mut fk(&["queue_id"], "queued_prompts", &["id"], Cascade))
            .check(check(r"kind IN ('project_file', 'project_directory', 'conversation')"))
            .check(check(r"truncated IN (0, 1)"))
            .check(check(r"(line_start IS NULL AND line_end IS NULL)
    OR (line_start > 0 AND line_end >= line_start)"))
        ),
        t(table("redaction_rules")
            .col(text("id").not_null().primary_key())
            .col(text("scope_type").not_null())
            .col(text("scope_id").not_null())
            .col(text("name").not_null())
            .col(text("description").not_null())
            .col(text("pattern").not_null())
            .col(text("category").not_null())
            .col(text("examples").not_null())
            .col(text("origin").not_null())
            .col(text("source_conversation_id"))
            .col(integer("is_enabled").not_null().default(1i64))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .index(&mut unique(&["scope_type", "scope_id", "name"]))
            .check(check(r"scope_type IN ('global', 'project')"))
            .check(check(r"category IN ('secret', 'pii', 'network')"))
            .check(check(r"origin IN ('model', 'user')"))
            .check(check(r"is_enabled IN (0, 1)"))
            .check(check(r"(scope_type = 'global' AND scope_id = '_') OR (scope_type = 'project' AND scope_id <> '_')"))
        ),
        t(table("acp_session_notices")
            .col(text("id").not_null().primary_key())
            .col(text("conversation_id").not_null())
            .col(text("turn_id"))
            .col(text("notice_id").not_null())
            .col(integer("revision").not_null())
            .col(text("category").not_null())
            .col(text("severity").not_null())
            .col(text("title").not_null())
            .col(text("details"))
            .col(text("reason"))
            .col(text("actions").not_null())
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .index(&mut unique(&["conversation_id", "notice_id"]))
            .foreign_key(&mut fk(&["conversation_id"], "conversations", &["id"], Cascade))
            .check(check(r"revision >= 0"))
            .check(check(r"category IN ('connection', 'access', 'limit', 'request', 'service', 'unknown')"))
            .check(check(r"severity IN ('warning', 'error')"))
            .check(check(r"json_valid(actions) AND json_type(actions) = 'array'"))
        ),
        t(table("notification_alert_state")
            .col(text("alert_key").not_null().primary_key())
            .col(big_int("first_raised_at").not_null())
            .col(big_int("last_raised_at").not_null())
            .col(big_int("last_notified_at"))
            .col(text("fingerprint").not_null())
        ),
        t(table("notification_webhooks")
            .col(text("id").not_null().primary_key())
            .col(text("name").not_null())
            .col(text("url").not_null())
            .col(text("format").not_null())
            .col(text("events").not_null())
            .col(integer("is_enabled").not_null().default(1i64))
            .col(text("body_template"))
            .col(big_int("last_attempt_at"))
            .col(big_int("last_success_at"))
            .col(text("last_error"))
            .col(integer("consecutive_failures").not_null().default(0i64))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .check(check(r"format IN ('generic', 'dingtalk', 'feishu', 'wecom', 'slack', 'custom')"))
            .check(check(r"is_enabled IN (0, 1)"))
            .check(check(r"consecutive_failures >= 0"))
        ),
        t(table("model_profiles")
            .col(text("id").not_null().primary_key())
            .col(text("name").not_null())
            .col(integer("context_window").not_null())
            .col(integer("compact_threshold").not_null())
            .col(integer("max_output_tokens"))
            .col(text("input_price"))
            .col(text("output_price"))
            .col(text("cache_read_price"))
            .col(text("cache_write_price"))
            .col(text("pricing_tiers"))
            .col(text("capability_overrides"))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .check(check(r"input_price IS NULL OR input_price = '0' OR (
            typeof(input_price) = 'text'
            AND length(input_price) > 0
            AND input_price NOT GLOB '*[^0-9.]*'
            AND input_price NOT LIKE '%.%.%'
            AND (substr(input_price, 1, 1) <> '0' OR substr(input_price, 2, 1) = '.')
            AND (instr(input_price, '.') = 0 OR (
                instr(input_price, '.') BETWEEN 2 AND length(input_price) - 1
                AND substr(input_price, -1, 1) GLOB '[1-9]'
            ))
            AND length(CASE WHEN instr(input_price, '.') = 0 THEN input_price
                            ELSE substr(input_price, 1, instr(input_price, '.') - 1) END) <= 20
            AND (instr(input_price, '.') = 0
                 OR length(input_price) - instr(input_price, '.') <= 18)
        )"))
            .check(check(r"output_price IS NULL OR output_price = '0' OR (
            typeof(output_price) = 'text'
            AND length(output_price) > 0
            AND output_price NOT GLOB '*[^0-9.]*'
            AND output_price NOT LIKE '%.%.%'
            AND (substr(output_price, 1, 1) <> '0' OR substr(output_price, 2, 1) = '.')
            AND (instr(output_price, '.') = 0 OR (
                instr(output_price, '.') BETWEEN 2 AND length(output_price) - 1
                AND substr(output_price, -1, 1) GLOB '[1-9]'
            ))
            AND length(CASE WHEN instr(output_price, '.') = 0 THEN output_price
                            ELSE substr(output_price, 1, instr(output_price, '.') - 1) END) <= 20
            AND (instr(output_price, '.') = 0
                 OR length(output_price) - instr(output_price, '.') <= 18)
        )"))
            .check(check(r"cache_read_price IS NULL OR cache_read_price = '0' OR (
            typeof(cache_read_price) = 'text'
            AND length(cache_read_price) > 0
            AND cache_read_price NOT GLOB '*[^0-9.]*'
            AND cache_read_price NOT LIKE '%.%.%'
            AND (substr(cache_read_price, 1, 1) <> '0' OR substr(cache_read_price, 2, 1) = '.')
            AND (instr(cache_read_price, '.') = 0 OR (
                instr(cache_read_price, '.') BETWEEN 2 AND length(cache_read_price) - 1
                AND substr(cache_read_price, -1, 1) GLOB '[1-9]'
            ))
            AND length(CASE WHEN instr(cache_read_price, '.') = 0 THEN cache_read_price
                            ELSE substr(cache_read_price, 1, instr(cache_read_price, '.') - 1) END) <= 20
            AND (instr(cache_read_price, '.') = 0
                 OR length(cache_read_price) - instr(cache_read_price, '.') <= 18)
        )"))
            .check(check(r"cache_write_price IS NULL OR cache_write_price = '0' OR (
            typeof(cache_write_price) = 'text'
            AND length(cache_write_price) > 0
            AND cache_write_price NOT GLOB '*[^0-9.]*'
            AND cache_write_price NOT LIKE '%.%.%'
            AND (substr(cache_write_price, 1, 1) <> '0' OR substr(cache_write_price, 2, 1) = '.')
            AND (instr(cache_write_price, '.') = 0 OR (
                instr(cache_write_price, '.') BETWEEN 2 AND length(cache_write_price) - 1
                AND substr(cache_write_price, -1, 1) GLOB '[1-9]'
            ))
            AND length(CASE WHEN instr(cache_write_price, '.') = 0 THEN cache_write_price
                            ELSE substr(cache_write_price, 1, instr(cache_write_price, '.') - 1) END) <= 20
            AND (instr(cache_write_price, '.') = 0
                 OR length(cache_write_price) - instr(cache_write_price, '.') <= 18)
        )"))
            .check(check(r"pricing_tiers IS NULL OR (json_valid(pricing_tiers) AND json_type(pricing_tiers) = 'array')"))
        ),
        t(table("model_configs")
            .col(text("id").not_null().primary_key())
            .col(text("provider_id").not_null())
            .col(text("model_id").not_null())
            .col(text("profile_id").not_null())
            .col(integer("overrides_pricing").not_null().default(0i64))
            .col(text("input_price"))
            .col(text("output_price"))
            .col(text("cache_read_price"))
            .col(text("cache_write_price"))
            .col(text("pricing_tiers"))
            .col(text("server_tools"))
            .col(text("server_tool_price"))
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .index(&mut unique(&["provider_id", "model_id"]))
            .foreign_key(&mut fk(&["profile_id"], "model_profiles", &["id"], NoAction))
            .foreign_key(&mut fk(&["provider_id"], "providers", &["id"], Cascade))
            .check(check(r"overrides_pricing IN (0, 1)"))
            .check(check(r"input_price IS NULL OR input_price = '0' OR (
            typeof(input_price) = 'text'
            AND length(input_price) > 0
            AND input_price NOT GLOB '*[^0-9.]*'
            AND input_price NOT LIKE '%.%.%'
            AND (substr(input_price, 1, 1) <> '0' OR substr(input_price, 2, 1) = '.')
            AND (instr(input_price, '.') = 0 OR (
                instr(input_price, '.') BETWEEN 2 AND length(input_price) - 1
                AND substr(input_price, -1, 1) GLOB '[1-9]'
            ))
            AND length(CASE WHEN instr(input_price, '.') = 0 THEN input_price
                            ELSE substr(input_price, 1, instr(input_price, '.') - 1) END) <= 20
            AND (instr(input_price, '.') = 0
                 OR length(input_price) - instr(input_price, '.') <= 18)
        )"))
            .check(check(r"output_price IS NULL OR output_price = '0' OR (
            typeof(output_price) = 'text'
            AND length(output_price) > 0
            AND output_price NOT GLOB '*[^0-9.]*'
            AND output_price NOT LIKE '%.%.%'
            AND (substr(output_price, 1, 1) <> '0' OR substr(output_price, 2, 1) = '.')
            AND (instr(output_price, '.') = 0 OR (
                instr(output_price, '.') BETWEEN 2 AND length(output_price) - 1
                AND substr(output_price, -1, 1) GLOB '[1-9]'
            ))
            AND length(CASE WHEN instr(output_price, '.') = 0 THEN output_price
                            ELSE substr(output_price, 1, instr(output_price, '.') - 1) END) <= 20
            AND (instr(output_price, '.') = 0
                 OR length(output_price) - instr(output_price, '.') <= 18)
        )"))
            .check(check(r"cache_read_price IS NULL OR cache_read_price = '0' OR (
            typeof(cache_read_price) = 'text'
            AND length(cache_read_price) > 0
            AND cache_read_price NOT GLOB '*[^0-9.]*'
            AND cache_read_price NOT LIKE '%.%.%'
            AND (substr(cache_read_price, 1, 1) <> '0' OR substr(cache_read_price, 2, 1) = '.')
            AND (instr(cache_read_price, '.') = 0 OR (
                instr(cache_read_price, '.') BETWEEN 2 AND length(cache_read_price) - 1
                AND substr(cache_read_price, -1, 1) GLOB '[1-9]'
            ))
            AND length(CASE WHEN instr(cache_read_price, '.') = 0 THEN cache_read_price
                            ELSE substr(cache_read_price, 1, instr(cache_read_price, '.') - 1) END) <= 20
            AND (instr(cache_read_price, '.') = 0
                 OR length(cache_read_price) - instr(cache_read_price, '.') <= 18)
        )"))
            .check(check(r"cache_write_price IS NULL OR cache_write_price = '0' OR (
            typeof(cache_write_price) = 'text'
            AND length(cache_write_price) > 0
            AND cache_write_price NOT GLOB '*[^0-9.]*'
            AND cache_write_price NOT LIKE '%.%.%'
            AND (substr(cache_write_price, 1, 1) <> '0' OR substr(cache_write_price, 2, 1) = '.')
            AND (instr(cache_write_price, '.') = 0 OR (
                instr(cache_write_price, '.') BETWEEN 2 AND length(cache_write_price) - 1
                AND substr(cache_write_price, -1, 1) GLOB '[1-9]'
            ))
            AND length(CASE WHEN instr(cache_write_price, '.') = 0 THEN cache_write_price
                            ELSE substr(cache_write_price, 1, instr(cache_write_price, '.') - 1) END) <= 20
            AND (instr(cache_write_price, '.') = 0
                 OR length(cache_write_price) - instr(cache_write_price, '.') <= 18)
        )"))
            .check(check(r"pricing_tiers IS NULL OR (json_valid(pricing_tiers) AND json_type(pricing_tiers) = 'array')"))
            .check(check(r"server_tool_price IS NULL OR server_tool_price = '0' OR (
            typeof(server_tool_price) = 'text'
            AND length(server_tool_price) > 0
            AND server_tool_price NOT GLOB '*[^0-9.]*'
            AND server_tool_price NOT LIKE '%.%.%'
            AND (substr(server_tool_price, 1, 1) <> '0' OR substr(server_tool_price, 2, 1) = '.')
            AND (instr(server_tool_price, '.') = 0 OR (
                instr(server_tool_price, '.') BETWEEN 2 AND length(server_tool_price) - 1
                AND substr(server_tool_price, -1, 1) GLOB '[1-9]'
            ))
            AND length(CASE WHEN instr(server_tool_price, '.') = 0 THEN server_tool_price
                            ELSE substr(server_tool_price, 1, instr(server_tool_price, '.') - 1) END) <= 20
            AND (instr(server_tool_price, '.') = 0
                 OR length(server_tool_price) - instr(server_tool_price, '.') <= 18)
        )"))
        ),
        t(table("composer_drafts")
            .col(text("slot").not_null().primary_key())
            .col(text("conversation_id"))
            .col(text("body").not_null())
            .col(text("attachments").not_null())
            .col(text("conversation_refs").not_null())
            .col(text("sticker_id"))
            .col(big_int("revision").not_null())
            .col(big_int("created_at").not_null())
            .col(big_int("updated_at").not_null())
            .index(&mut unique(&["conversation_id"]))
            .foreign_key(&mut fk(&["sticker_id"], "emojis", &["id"], SetNull))
            .foreign_key(&mut fk(&["conversation_id"], "conversations", &["id"], Cascade))
            .check(check(r"revision > 0"))
            .check(check(r"(slot = 'new' AND conversation_id IS NULL)
    OR (conversation_id IS NOT NULL AND slot = 'conversation:' || conversation_id)"))
        ),
        index("idx_acp_session_notices_conversation", "acp_session_notices", &[("conversation_id", Asc), ("created_at", Asc)], false, None),
        index("idx_acp_sessions_session", "acp_sessions", &[("acp_session_id", Asc)], true, None),
        index("idx_audit_conversation_turn", "audit_messages", &[("conversation_id", Asc), ("turn_id", Asc)], false, None),
        index("idx_audit_created", "audit_messages", &[("created_at", Asc)], false, None),
        index("idx_audit_provider_model", "audit_messages", &[("provider_id", Asc), ("model_id", Asc)], false, None),
        index("idx_audit_sender", "audit_messages", &[("sender_id", Asc)], false, Some(r"sender_id IS NOT NULL")),
        index("idx_cached_models_provider", "cached_models", &[("provider_id", Asc)], false, None),
        index("idx_cached_models_unique", "cached_models", &[("provider_id", Asc), ("model_id", Asc)], true, None),
        index("idx_conversations_pinned", "conversations", &[("is_pinned", Desc), ("updated_at", Desc)], false, None),
        index("idx_conversations_updated", "conversations", &[("updated_at", Desc)], false, None),
        index("idx_emoji_packs_source_account", "emoji_packs", &[("kind", Asc), ("source_account_id", Asc)], true, Some(r"source_account_id IS NOT NULL")),
        index("idx_emojis_pack", "emojis", &[("pack_id", Asc), ("sort_order", Asc)], false, None),
        index("idx_emojis_pack_name", "emojis", &[("pack_id", Asc), ("name", Asc)], true, None),
        index("idx_emojis_semantic_status", "emojis", &[("pack_id", Asc), ("semantic_status", Asc), ("last_seen_at", Asc)], false, None),
        index("idx_emojis_source_key", "emojis", &[("pack_id", Asc), ("source", Asc), ("source_key", Asc)], true, Some(r"source_key IS NOT NULL")),
        index("idx_journal_files_path", "journal_files", &[("norm_path", Asc)], true, None),
        index("idx_journal_versions_conv", "journal_versions", &[("conversation_id", Asc)], false, None),
        index("idx_journal_versions_seq", "journal_versions", &[("file_id", Asc), ("seq", Asc)], true, None),
        index("idx_journal_versions_turn", "journal_versions", &[("turn_id", Asc)], false, None),
        index("idx_memories_scope_key", "memories", &[("scope_type", Asc), ("scope_id", Asc), ("key", Asc)], true, Some(r"deleted_at IS NULL")),
        index("idx_memories_subject", "memories", &[("subject_scope_id", Asc)], false, Some(r"deleted_at IS NULL")),
        index("idx_memory_proposals_status", "memory_proposals", &[("status", Asc), ("expires_at", Asc)], false, None),
        index("idx_memory_subjects_last_seen", "memory_subjects", &[("last_seen_at", Asc)], false, None),
        index("idx_message_context_items_message", "message_context_items", &[("message_id", Asc), ("position", Asc)], false, None),
        index("idx_message_stickers_sticker", "message_stickers", &[("sticker_id", Asc)], false, None),
        index("idx_messages_conversation", "messages", &[("conversation_id", Asc), ("sort_order", Asc)], false, None),
        index("idx_messages_parent", "messages", &[("parent_id", Asc)], false, None),
        index("idx_mode_artifacts_approved", "mode_artifacts", &[("conversation_id", Asc), ("kind", Asc)], true, Some(r"status = 'approved'")),
        index("idx_mode_artifacts_conversation", "mode_artifacts", &[("conversation_id", Asc), ("kind", Asc), ("created_at", Asc)], false, None),
        index("idx_model_configs_profile", "model_configs", &[("profile_id", Asc)], false, None),
        index("idx_notification_webhooks_enabled", "notification_webhooks", &[("is_enabled", Asc)], false, None),
        index("idx_plan_comments_review", "plan_comments", &[("review_id", Asc), ("position", Asc)], false, None),
        index("idx_plan_deliveries_state", "plan_review_deliveries", &[("state", Asc), ("created_at", Asc)], false, None),
        index("idx_plan_documents_active", "plan_documents", &[("conversation_id", Asc)], true, Some(r"state IN ('drafting', 'reviewing', 'approved')")),
        index("idx_plan_documents_conversation", "plan_documents", &[("conversation_id", Asc), ("created_at", Asc)], false, None),
        index("idx_plan_materializations_pending", "plan_materializations", &[("state", Asc), ("created_at", Asc)], false, None),
        index("idx_plan_reviews_document", "plan_review_sessions", &[("document_id", Asc), ("created_at", Asc)], false, None),
        index("idx_plan_reviews_pending", "plan_review_sessions", &[("document_id", Asc)], true, Some(r"state = 'pending'")),
        index("idx_plan_revisions_content_sha", "plan_revisions", &[("document_id", Asc), ("content_sha256", Asc)], false, None),
        index("idx_plan_revisions_document", "plan_revisions", &[("document_id", Asc), ("revision_no", Asc)], false, None),
        index("idx_projects_source", "projects", &[("source_type", Asc), ("source_id", Asc)], true, Some(r"source_id IS NOT NULL")),
        index("idx_queued_prompt_context_items_queue", "queued_prompt_context_items", &[("queue_id", Asc), ("position", Asc)], false, None),
        index("idx_queued_prompts_conversation", "queued_prompts", &[("conversation_id", Asc), ("position", Asc)], false, None),
        index("idx_queued_prompts_unreported", "queued_prompts", &[("conversation_id", Asc), ("reported_at", Asc)], false, Some(r"dispatched_at IS NOT NULL AND settled_at IS NULL")),
        index("idx_redaction_rules_scope", "redaction_rules", &[("scope_type", Asc), ("scope_id", Asc), ("is_enabled", Asc)], false, None),
        index("idx_skills_llm_name", "skills", &[("llm_name", Asc)], false, None),
        index("idx_todo_items_list", "todo_items", &[("list_id", Asc), ("sort_order", Asc)], false, None),
        index("idx_todo_lists_active", "todo_lists", &[("conversation_id", Asc)], true, Some(r"status = 'in_progress'")),
        index("idx_todo_lists_conversation", "todo_lists", &[("conversation_id", Asc), ("created_at", Asc)], false, None),
        index("idx_turns_conversation", "turns", &[("conversation_id", Asc), ("started_at", Asc)], false, None),
        index("idx_voice_blobs_dedupe", "voice_blobs", &[("bot_self_id", Asc), ("source_type", Asc), ("source_id", Asc), ("file_format", Asc), ("sha256", Asc)], true, None),
        index("idx_voice_blobs_status", "voice_blobs", &[("status", Asc), ("lease_expires_at", Asc)], false, None),
        index("idx_voice_clips_blob", "voice_clips", &[("blob_id", Asc)], false, None),
        index("idx_voice_clips_occurrence", "voice_clips", &[("bot_self_id", Asc), ("source_type", Asc), ("source_id", Asc), ("platform_message_id", Asc), ("segment_index", Asc)], true, Some(r"platform_message_id IS NOT NULL")),
        index("idx_voice_clips_sender", "voice_clips", &[("sender_id", Asc)], false, None),
        trigger(r"CREATE TRIGGER trg_messages_count_delete AFTER DELETE ON messages BEGIN UPDATE conversations SET message_count = message_count - 1 WHERE id = OLD.conversation_id; END"),
        trigger(r"CREATE TRIGGER trg_messages_count_insert AFTER INSERT ON messages BEGIN UPDATE conversations SET message_count = message_count + 1, updated_at = NEW.created_at WHERE id = NEW.conversation_id; END"),
        trigger(r"CREATE TRIGGER trg_messages_sort_order AFTER INSERT ON messages FOR EACH ROW WHEN NEW.sort_order = 0 BEGIN UPDATE messages SET sort_order = ( SELECT COALESCE(MAX(sort_order), 0) + 1 FROM messages WHERE conversation_id = NEW.conversation_id ) WHERE id = NEW.id; END"),
    ]
}
