//! Writes `migration/m0001_baseline.rs` from a schema read back out of a
//! database — one the 65 Diesel migrations built. Run through
//! `examples/gen_baseline.rs`; what it emits is checked in, and the
//! equivalence tests hold the checked-in file to the replayed schema.
//!
//! The output is written in the vocabulary of `migration/mod.rs` so that it
//! reads as a schema. Anything the generator does not know how to express —
//! a default that is not a literal, an index on an expression — is a panic
//! here rather than a guess in the output.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use super::introspect::{Column, ForeignKey, Index, Schema, Table};

const HEADER: &str = "\
//! The schema as the 65 Diesel migrations left it, as one SeaORM migration.
//!
//! GENERATED by `cargo run -p meridian-core --example gen_baseline --features test-support`
//! from a database those migrations produced; do not edit by hand. The
//! equivalence tests in `db/sea/equivalence_tests.rs` compare what this builds
//! with what replaying the migrations builds, table by table.
//!
//! Column types are the declared ones: `BIGINT` is `big_int`, `INTEGER` is
//! `integer`, and both render as `integer` on SQLite, where the distinction is
//! one of affinity only. `CHECK` expressions, the `WHERE` of a partial index
//! and the three triggers are SQLite text, passed through — see the
//! `backend: sqlite-only` notes in `migration/mod.rs`.

";

const BODY: &str = "
/// The statements SQLite runs for the baseline, in order.
pub fn sqlite_statements() -> Vec<String> {
    render_sqlite(&objects())
}

#[rustfmt::skip]
pub(super) fn objects() -> Vec<Object> {
    vec![
";

const FOOTER: &str = "    ]
}
";

/// Which names the generated code uses, so that it imports those and no
/// others: an unused import is a warning, and warnings are errors here.
#[derive(Default)]
struct Used {
    helpers: BTreeSet<&'static str>,
    actions: BTreeSet<&'static str>,
    orders: BTreeSet<&'static str>,
}

/// The Rust source of the baseline module for `schema`.
pub fn render(schema: &Schema) -> String {
    let mut used = Used::default();
    used.helpers.extend(["Object", "render_sqlite"]);
    let mut body = String::new();
    for table in &schema.tables {
        render_table(&mut body, table, &mut used);
    }
    for index in &schema.indexes {
        render_index(&mut body, index, &mut used);
    }
    for trigger in &schema.triggers {
        used.helpers.insert("trigger");
        writeln!(body, "        trigger({}),", raw_string(&trigger.sql)).unwrap();
    }

    let mut out = String::from(HEADER);
    let list = |names: &BTreeSet<&str>| names.iter().copied().collect::<Vec<_>>().join(", ");
    if !used.actions.is_empty() {
        writeln!(
            out,
            "use sea_orm::sea_query::ForeignKeyAction::{{{}}};",
            list(&used.actions)
        )
        .unwrap();
    }
    if !used.orders.is_empty() {
        writeln!(out, "use sea_orm::sea_query::IndexOrder::{{{}}};", list(&used.orders)).unwrap();
    }
    writeln!(out, "\nuse super::{{{}}};", list(&used.helpers)).unwrap();
    out.push_str(BODY);
    out.push_str(&body);
    out.push_str(FOOTER);
    out
}

fn render_table(out: &mut String, table: &Table, used: &mut Used) {
    used.helpers.extend(["t", "table"]);
    writeln!(out, "        t(table({:?})", table.name).unwrap();
    let single_key = table.primary_key.len() == 1;
    for column in &table.columns {
        writeln!(
            out,
            "            .col({})",
            render_column(column, single_key, table.autoincrement, used)
        )
        .unwrap();
    }
    if !single_key && !table.primary_key.is_empty() {
        used.helpers.insert("key");
        writeln!(out, "            .primary_key(&mut key(&{:?}))", table.primary_key).unwrap();
    }
    for unique_columns in &table.uniques {
        used.helpers.insert("unique");
        writeln!(out, "            .index(&mut unique(&{unique_columns:?}))").unwrap();
    }
    for foreign_key in &table.foreign_keys {
        used.helpers.insert("fk");
        writeln!(
            out,
            "            .foreign_key(&mut {})",
            render_foreign_key(foreign_key, used)
        )
        .unwrap();
    }
    for clause in &table.checks {
        used.helpers.insert("check");
        writeln!(out, "            .check(check({}))", raw_string(clause)).unwrap();
    }
    out.push_str("        ),\n");
}

fn render_column(column: &Column, single_key: bool, autoincrement: bool, used: &mut Used) -> String {
    let constructor = match column.declared_type.to_ascii_uppercase().as_str() {
        "TEXT" => "text",
        "INTEGER" => "integer",
        "BIGINT" => "big_int",
        "REAL" => "double",
        other => panic!(
            "column {} has a declared type the generator does not map: {other:?}",
            column.name
        ),
    };
    used.helpers.insert(constructor);
    let mut rendered = format!("{constructor}({:?})", column.name);
    if column.not_null {
        rendered.push_str(".not_null()");
    }
    if let Some(default) = &column.default {
        write!(rendered, ".default({})", render_default(default, &column.name)).unwrap();
    }
    if column.in_primary_key && single_key {
        rendered.push_str(".primary_key()");
        if autoincrement {
            rendered.push_str(".auto_increment()");
        }
    }
    rendered
}

/// `pragma_table_info` reports the default as SQL text. Only two shapes
/// occur: an integer literal and a single-quoted string.
fn render_default(sql: &str, column: &str) -> String {
    if let Ok(number) = sql.parse::<i64>() {
        return format!("{number}i64");
    }
    if sql.len() >= 2 && sql.starts_with('\'') && sql.ends_with('\'') {
        let inner = sql[1..sql.len() - 1].replace("''", "'");
        return format!("{inner:?}");
    }
    panic!("column {column} has a default the generator does not map: {sql:?}");
}

fn render_foreign_key(foreign_key: &ForeignKey, used: &mut Used) -> String {
    let action = match foreign_key.on_delete.as_str() {
        "CASCADE" => "Cascade",
        "SET NULL" => "SetNull",
        "RESTRICT" => "Restrict",
        "NO ACTION" => "NoAction",
        other => panic!("foreign key action the generator does not map: {other:?}"),
    };
    used.actions.insert(action);
    assert_eq!(
        foreign_key.on_update, "NO ACTION",
        "the vocabulary has no ON UPDATE; {foreign_key:?} needs one"
    );
    format!(
        "fk(&{:?}, {:?}, &{:?}, {action})",
        foreign_key.columns, foreign_key.references_table, foreign_key.references_columns
    )
}

fn render_index(out: &mut String, index: &Index, used: &mut Used) {
    used.helpers.insert("index");
    let columns: Vec<String> = index
        .columns
        .iter()
        .map(|column| {
            let order = if column.descending { "Desc" } else { "Asc" };
            used.orders.insert(order);
            format!("({:?}, {order})", column.name)
        })
        .collect();
    let filter = match &index.where_clause {
        Some(clause) => format!("Some({})", raw_string(clause)),
        None => "None".to_owned(),
    };
    writeln!(
        out,
        "        index({:?}, {:?}, &[{}], {}, {filter}),",
        index.name,
        index.table,
        columns.join(", "),
        index.unique
    )
    .unwrap();
}

/// A raw string literal holding `text` verbatim, with as many `#` as it takes.
fn raw_string(text: &str) -> String {
    let mut hashes = String::new();
    while text.contains(&format!("\"{hashes}")) {
        hashes.push('#');
    }
    format!("r{hashes}\"{text}\"{hashes}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn raw_strings_grow_hashes_until_the_text_cannot_close_them() {
        assert_eq!(raw_string("a"), "r\"a\"");
        assert_eq!(raw_string("say \"hi\""), "r#\"say \"hi\"\"#");
        assert_eq!(raw_string("x\"#y"), "r##\"x\"#y\"##");
    }

    #[test]
    fn defaults_are_literals_or_nothing() {
        assert_eq!(render_default("0", "c"), "0i64");
        assert_eq!(render_default("'user'", "c"), "\"user\"");
        assert_eq!(render_default("'it''s'", "c"), "\"it's\"");
        assert_eq!(
            render_default("'{\"type\":\"object\"}'", "c"),
            "\"{\\\"type\\\":\\\"object\\\"}\""
        );
    }

    #[test]
    #[should_panic(expected = "does not map")]
    fn an_expression_default_is_refused() {
        render_default("CURRENT_TIMESTAMP", "c");
    }
}
